### ISSUE TITLE
FEATURE: make form field required in CrudForms\FormField annotation

### ISSUE THREAD

**Issue by crydotsnake** [sandstorm/CrudForms#23]
## Description

Currently there is no possibility to set a form field to Required from within the package. It is possible to add the field in the model with the `NotEmpty` validator from Flow:

```php
/**
 * @Flow\Validate(type="NotEmpty")
 */
```

However, this does not look really nice afterwards for the editor:

![SCR-20231027-oeoy](https://github.com/sandstorm/CrudForms/assets/39345336/be28509f-74f1-4224-aeed-25c04f72bfc6)

## My Idea

What I was thinking about would be if I could set my field in the model to `required` directly in the `@CrudForms` annotation:

```php
/**
 * @CrudForms\FormField(label="Note Title", required=true)
 * @var string
 */
protected $noteTitle;
```

Then we could add an `if` condition to the respective editors (`/Sandstorm.CrudForms/Resources/Private/Partials/CrudForms/Helpers/Editor`). And if the `required` option is set to `true`, a hint message is displayed in the backend.

I'm still thinking about how to implement this in the most useful way, or if I might have to implement it differently. If you have feedback, I'm happy about it.

**Comment by crydotsnake** [comment]
For the `form.textfield` field you could add the `required` attribute:

```html
required="{field.required}"
```

And then you would get a feedback from the browser that this field is required:

![SCR-20231027-oyso](https://github.com/sandstorm/CrudForms/assets/39345336/40e1e65d-7778-4b21-abfc-1bdfd4561f45)

I only tested it with the `form.textfield` field. It would be a simple solution. But I am sure that it can be done even better.

**Comment by crydotsnake** [comment]
Your feedback would be very much appreciated! @skurfuerst

**Comment by skurfuerst** [comment]
Hey @crydotsnake ,

adding required=true to the CrudForm annotation seems like a pragmatic solution to me :) So I like that a lot :) Do you want to implement it? Please ping me in case I do not react in slack - if I do not react I simply missed the notification, no bad intentions :) 

All the best,
Sebastian

**Comment by crydotsnake** [comment]
Hello @skurfuerst 

Thanks for your feedback!

> adding required=true to the CrudForm annotation seems like a pragmatic solution to me :) So I like that a lot :) Do you want to implement it?

Sure, i can take care of it :)

> Please ping me in case I do not react in slack - if I do not react I simply missed the notification, no bad intentions :)

All good Sebastian! - I will ping you, in case i need more feedback. Thanks! ❤️
